# Plugins
plugins:
- jekyll-redirect-from
- jekyll-paginate
safe: false

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: [vendor, scripts, README.md, LICENSE.txt, CNAME]

# SASS Settings
sass:
  sass_dir: _sass
  line_comments: false
  relative_assets: true
  style: compressed

# Site Settings
title: "Technology Robotix Society, IIT Kharagpur"
description: "Technology Robotix Society is an official society under the Technology Students' Gymkhana IIT Kharagpur."
baseurl: "https://2023.robotix.in"
permalink: "/blog/:title/"
collections:
  events:
    output: true
    permalink: "/event/:path/"
  tutorials:
    output: true
    permalink: "/tutorial/:path/"
  workshops:
      output: true
      permalink: "/workshops/:path/"

#Pagination
paginate: 10
paginate_path: "/blog/:num"

# Head
metaKeywords: "robotix, robotics, iit, kgp, team, events, society, technology, tutorial"
twitterAccount: "@robotixiitkgp"
google-plus-page: "https://plus.google.com/102868621563384739622"
siteVerification: "ZR618hQWwV_OwtWa033492kzvBaQYxBc1ZauYc5oO5A"
socialImage: "/img/favicons/favicon-196x196.png"

# Navigation
navigationLinks:
 - {link: "https://makerspace.robotix.in/", text: "Makerspace"}
 - {permalink: "/FAQs/", text: "FAQs"}
 - {permalink: "/workshops/", text: "Workshops"}
 - {permalink: "/event/", text: "Events"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/tutorial", text: "Tutorials"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/about-us/", text: "About Us"}
bottomNavigationLinks:
 - {link: "https://robotix.typeform.com/to/USirXsoq", text: "Contact Us"}


# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout>"
eventDate: "20th Jan - 22nd Jan, 2023"
typeoutTextValues: '"Technology Robotix Society", "Where Machines Dare!", "#GearUp", "Robotix 2023"'
typeoutFallback: "Technology Robotix Society"
heroButtons:
   - {permalink: "/event/", text: "Explore Events"}

# About Block
aboutTitle: "We believe in sharing our knowledge"
aboutBlock:
  -
    title: "K.R.A.I.G."
    image: "kraig.jpg"
    text: "Kickstart your journey into the world of hobby robotics."
    link: "/kraig/"
  -
    title: "K.R.I.S.S."
    image: "kriss.jpg"
    text: "To bring together people, to discuss and exchange ideas related to more mature and nuanced areas of robotics."
    link: "/kriss/"
  -
    title: "Winter Workshop"
    image: "winter-workshop.png"
    text: "See the complete documentation of the winter workshop we conduct anually for first and second year undergraduates of IIT Kharagpur."
    link: "/winter-workshop/"

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 # - {count: "2000", specialCharacter: "+", info: "participants"}
 # - {count: "500", specialCharacter: "+", info: "teams"}
 - {count: "3", specialCharacter: "", info: "events"}
 - {count: "1", specialCharacter: "", info: "fest"}
statisticQuirk: "Robotix 2023, #GearUp"

# Latest News Block
latestNewsTitle: "Latest blog articles"
latestNewsCount: 2
latestNewsButtonText: "Explore our blog"

# Facebook Feed Block
FbFeedTitle: "Are You Geared Up?"
FbHashTag: "robotixiitkgp"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://robotix.us8.list-manage.com/subscribe/post?u=175d25a13bb44ffe7478a4ccf&amp;id=8de4186fe7"
subscribeInfo: "Subscribe with us to stay tuned!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/102868621563384739622/", icon: "google-plus"}
 - {link: "https://twitter.com/RobotixIITKgp", icon: "twitter"}
 - {link: "https://facebook.com/robotixiitkgp", icon: "facebook"}
 - {link: "https://www.youtube.com/robotixiitkgp", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   # - {link: "http://app.robotix.in", text: "Robotix App"}
   - {link: "https://drive.google.com/open?id=1jNJHFE1QjGOHFwhhzn6e774odGv-6eFQ", text: "Robotix App"}
   - {link: "https://robotix.in/event/", text: "Events"}
   - {link: "https://robotix.in/tutorial/", text: "Tutorials"}
 -
  title: "Contacts"
  links:
   - {link: "https://robotix.typeform.com/to/USirXsoq", text: "Contact Us"}
 -
  title: "Archives"
  links:
   - {link: "https://2020.robotix.in/", text: "Robotix 2020"}
   - {link: "https://2019.robotix.in/", text: "Robotix 2019"}
   - {link: "https://2018.robotix.in/", text: "Robotix 2018"}
   - {link: "https://2017.robotix.in/", text: "Robotix 2017"}
   - {link: "https://2016.robotix.in/", text: "Robotix 2016"}

# Blog
blogCommentsEnabled: true
discusShortName: "robotix"

# Speakers List Block
showSessions: true

google_analytics: UA-83617238-1

#AboutUs
whoAreWe: "Technology Robotix Society is an official society under the Technology Students' Gymkhana, IIT Kharagpur, and is a focal point for activities and projects related to robotics in the campus. With its reach expanding steadily each year, it has also cemented its position as one of the nerve centres of amateur robotics in India."
whatDoWeDo: "We are involved in various initiatives in the field of robotics throughout the year. Our flagship accomplishment is our annual competition ROBOTIX, which is held during KSHITIJ at IIT Kharagpur, and is one of the biggest such events in Asia. Every year we have increasingly capable and motivated participants tackling our novel problem statements and thereby inspiring us to organize each year's fest with renewed zeal. Another important agenda of ours is to spread the culture of robotics across India and we do this by organizing and conducting workshops and demonstrations, and in Kharagpur, besides this, by other in-house events too."
